<link href="../includes/layout/<?=$theme?>/css/estilon.css" rel="stylesheet" type="text/css" />
<script type="text/javascript" src="../includes/JQuery/jquery2.js"></script>
<script type="text/javascript" src="../includes/JQuery/jquery.accordion.source.js" charset="utf-8"></script>
<script type="text/javascript">
// <![CDATA[
$(document).ready(function () {
	if($('ul'))
		$('ul').accordion();
});
// ]]>
</script>