<?php
/*
$obras = new Obras();


switch($_REQUEST['acao']){
// Adicionar/Atualizar execução orçamentária
case "H":
	$obras->RegistrarExecucaoOrcamentaria($_REQUEST);
break;
	case "C":
	$obras->CadastrarObras($_REQUEST);
break;
case "E":
	$obras->DeletarObras($_REQUEST["obrid"]);
break;
case "U":
		$obras->AtualizarObras($_REQUEST);
break;
case "F":
	$obras->CadastrarContratacaoObras($_REQUEST);
break;
case "CR":
	$obras->CadastrarCronogramaObras($_REQUEST);
break;
case "V":
	$obras->CadastrarVistoria($_REQUEST);
break;	
case "X":
	$obras->AtualizarVistoria($_REQUEST);
break;	
case "Z":
	$obras->DeletarVistoria($_REQUEST["supvid"]);
break;
case "P":
	$obras->CadastrarProjetoArquitetonico($_REQUEST);
break;
case "I":
	$obras->CadastrarInfraEstrutura($_REQUEST);	
break;

case "T":
	$obras->AtualizarFotosVistoria($_REQUEST);
break;
case "K":
	$obras->ShowImage($_REQUEST["img"],$_REQUEST["dir"]);
break;
case "W":
	$obras->DeletarFotoVistoria($_REQUEST);
break;
case "Y":
	$obras->UpdateListFoto();	
break;
case "J":
	$obras->DeletarDocumento($_REQUEST);	
break;
case "L":
	$obras->DownloadArquivo($_REQUEST);	
break;
case "N":
	$obras->VerificaExistenciaVistorias($_REQUEST["supvid"]);	
break;

case "S":
	$obras->AtualizaComboUnidadeObra($_REQUEST["orgid"]);	
break;

default:

break;


}

//Gato - Refazer com tempo
if($_REQUEST["lista"]==1){ 
	$obras->AtualizaComboUnidadeObra($_REQUEST["orgao"]);
	exit();
}
*/
?>
