<?php

require_once( APPRAIZ . '/includes/planodetrabalho/comuns/arquivos_requeridos.inc' );
require_once( APPRAIZ . '/includes/planodetrabalho/tarefa_pt/tarefaPT.class.inc' );
require_once( APPRAIZ . '/includes/planodetrabalho/tarefa_pt/projetoPT.class.inc' );
require_once( APPRAIZ . '/includes/planodetrabalho/tarefa_acao/tarefaAcao.class.inc' );
require_once( APPRAIZ . '/includes/planodetrabalho/tarefa_acao/Acao.class.inc' );
require_once( APPRAIZ . '/includes/planodetrabalho/tarefa_acao/tabela_tarefasAcao.inc' );

?>