<?php
	
class Idioma extends Modelo{
	
    /**
     * Nome da tabela especificada
     * @var string
     * @access protected
     */
    protected $stNomeTabela = "gestaopessoa.idioma";	

    /**
     * Chave primaria.
     * @var array
     * @access protected
     */
    protected $arChavePrimaria = array( "fidif" );

    /**
     * Atributos
     * @var array
     * @access protected
     */    
    protected $arAtributos     = array(
									  	'fidif' => null, 
									  	'fdpcpf' => null, 
									  	'ftiid' => null, 
									  	'ftcidleitura' => null, 
									  	'ftcidfala' => null, 
									  	'ftcidescrita' => null, 
									  );
}