<?php

require_once( APPRAIZ . '/includes/planodetrabalho/comuns/AbstractEntity.class.inc' );
require_once( APPRAIZ . '/includes/planodetrabalho/comuns/ActiveFrozenField.class.inc' );
require_once( APPRAIZ . '/includes/planodetrabalho/comuns/ActiveFrozenFieldEntity.class.inc' );
require_once( APPRAIZ . '/includes/planodetrabalho/comuns/tarefa.class.inc' );
require_once( APPRAIZ . '/includes/planodetrabalho/comuns/projeto.class.inc' );
require_once( APPRAIZ . '/includes/planodetrabalho/comuns/usuario.class.inc' );
require_once( APPRAIZ . '/includes/planodetrabalho/comuns/library.inc' );

?>